### ISSUE TITLE
Many keyways fail to generate properly. Fix: set cutter_radius=0 in module key_blank.

### ISSUE THREAD

**Issue by 0itg** [ervanalb/keygen#5]
I discovered this while trying to generate a Primus key, but it seems to affect most Schlage keyways and possibly others. The default value for cutter_radius apparently cuts the blade in half with many keyway designs. At any rate, the final key has essentially no blade at all. Changing the default for cutter_radius to 0, (disabling this cut), seems like a safer choice, or else each .scad file should set its own value (as far as I can see the Schlage .scad files do not, though maybe others do).

**Comment by MrButlerTron** [comment]
Tested and can confirm it fixes for me as well in the scenarios I see. 
Have not tested everything.

Would this be something we can submit a pull request to update the code for?  Or is there some negative side effect?

**Comment by ervanalb** [comment]
Fixed in https://github.com/ervanalb/keygen/commit/7d12dc706706cb603eb5d690f546f55216d7de37
