### ISSUE TITLE
Keys not rendering properly

### ISSUE THREAD

**Issue by js802025** [ervanalb/keygen#8]
All/most of the keys appear to be rendering missing the center of the key:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/30957566/178605561-06fc9218-3846-446f-8d2e-2876ac7b290b.png">

There is a warning about how it is trying to scale a 2d object with 0. So it is removing the object.

**Comment by ervanalb** [comment]
Fixed in https://github.com/ervanalb/keygen/commit/7d12dc706706cb603eb5d690f546f55216d7de37
